In [2]:
import numpy as np

In [9]:
print(np.array([2,3,5,5]))
print(np.zeros(3))
print(np.ones(3))
print(np.random.rand(3))

[2 3 5 5]
[0. 0. 0.]
[1. 1. 1.]
[0.72685853 0.58873915 0.98289706]


In [23]:
print(np.array([1,2,3])*np.ones(3))
data = np.array([1,2,3])
print(data*3.4)
print(data[1:].std())

[1. 2. 3.]
[ 3.4  6.8 10.2]
0.5


In [72]:
mat=np.random.randint(10,50,(4,5))
data1=np.random.randint(5,10,(3,4))@mat
print(data1)
print(data1[1:2,2:3])
print(data1[1:,3:])
print(data1[2,4])


[[ 907 1081  877 1031 1017]
 [ 790 1027  844  948  864]
 [ 830  899  734  955  934]]
[[844]]
[[948 864]
 [955 934]]
934


In [81]:
print(data1.max(axis=0).reshape(5,1))
print(data1.max(axis=1))
print(data1.T)

[[ 907]
 [1081]
 [ 877]
 [1031]
 [1017]]
[1081 1027  955]
[[ 907  790  830]
 [1081 1027  899]
 [ 877  844  734]
 [1031  948  955]
 [1017  864  934]]


In [99]:
# step must be a number, not a tuple
dim_mat = np.arange(48).reshape(4,3,4)
dim_mat2 = np.arange(48,96).reshape(4,3,4)
print(dim_mat)


# MSE

error = 1/48 * np.sum(np.square(dim_mat-dim_mat2))


#     or pro method 

error2 = np.mean(np.square(dim_mat-dim_mat2))
print(error)
print(error2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
2304.0
2304.0
