In [2]:
import numpy as np

In [3]:
print(np.array([2,3,5,5]))
print(np.zeros(3))
print(np.ones(3))
print(np.random.rand(3))

[2 3 5 5]
[0. 0. 0.]
[1. 1. 1.]
[0.4859826  0.85597005 0.1743137 ]


In [4]:
print(np.array([1,2,3])*np.ones(3))
data = np.array([1,2,3])
print(data*3.4)
print(data[1:].std())

[1. 2. 3.]
[ 3.4  6.8 10.2]
0.5


In [5]:
mat=np.random.randint(10,50,(4,5))
data1=np.random.randint(5,10,(3,4))@mat
print(data1)
print(data1[1:2,2:3])
print(data1[1:,3:])
print(data1[2,4])


[[ 910  813  654  707 1165]
 [ 901  909  658  776 1219]
 [ 918  832  615  681 1178]]
[[658]]
[[ 776 1219]
 [ 681 1178]]
1178


In [6]:
print(data1.max(axis=0).reshape(5,1))
print(data1.max(axis=1))
print(data1.T)

[[ 918]
 [ 909]
 [ 658]
 [ 776]
 [1219]]
[1165 1219 1178]
[[ 910  901  918]
 [ 813  909  832]
 [ 654  658  615]
 [ 707  776  681]
 [1165 1219 1178]]


In [7]:
# step must be a number, not a tuple
dim_mat = np.arange(48).reshape(4,3,4)
dim_mat2 = np.arange(48,96).reshape(4,3,4)
print(dim_mat)


# MSE

error = 1/48 * np.sum(np.square(dim_mat-dim_mat2))


#     or pro method 

error2 = np.mean(np.square(dim_mat-dim_mat2))
print(error)
print(error2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
2304.0
2304.0


In [19]:

data = np.ones((5,5))
data[1:4,1:4]=0
data[2:3,2:3]=9
print(data)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [53]:
d = np.arange(1, 31).reshape(6, 5)
check=d[:4,1:]
identity=np.identity(4)>=1
check[identity]

# or 

d[[0,1,2,3],[1,2,3,4]]
d[[0,-2,-1],3:]
d[[-1,-2,-3,-4],[1,2,3,4]]

array([27, 23, 19, 15])